# Generated by Django 3.0.7 on 2020-06-24 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=30)),
                ('upload_picture_label', models.CharField(max_length=30)),
                ('user_name_label', models.CharField(max_length=30)),
                ('first_name_label', models.CharField(max_length=30)),
                ('middle_name_label', models.CharField(max_length=30)),
                ('last_name_label', models.CharField(max_length=30)),
                ('password_label', models.CharField(max_length=30)),
                ('dob_label', models.CharField(max_length=30)),
                ('email_label', models.CharField(max_length=30)),
                ('telephone_label', models.CharField(max_length=30)),
                ('address_label', models.CharField(max_length=30)),
                ('gender_label', models.CharField(max_length=30)),
                ('Male_label', models.CharField(max_length=30)),
                ('Female_label', models.CharField(max_length=30)),
                ('Other_label', models.CharField(max_length=30)),
                ('switch_label', models.CharField(max_length=30)),
                ('qualification_label', models.CharField(max_length=30)),
                ('role_label', models.CharField(max_length=30)),
                ('resume_label', models.CharField(max_length=30)),
                ('pan_card_label', models.CharField(max_length=30)),
                ('adhar_card_label', models.CharField(max_length=30)),
                ('submit_label', models.CharField(max_length=30)),
                ('company_label', models.CharField(max_length=30)),
                ('forgot_password_label', models.CharField(max_length=30)),
                ('Login_button_label', models.CharField(max_length=30)),
                ('register_button_label', models.CharField(max_length=30)),
                ('dashboard_label', models.CharField(max_length=30)),
                ('active_user_label', models.CharField(max_length=30)),
                ('inactive_user_label', models.CharField(max_length=30)),
                ('add_user_button', models.CharField(max_length=30)),
                ('dt_profile_label', models.CharField(max_length=30)),
                ('dt_resume_label', models.CharField(max_length=30)),
                ('dt_pan_card_label', models.CharField(max_length=30)),
                ('dt_adhar_card_label', models.CharField(max_length=30)),
                ('action_btn_label', models.CharField(max_length=30)),
                ('Menu_label', models.CharField(max_length=30)),
                ('logout_label', models.CharField(max_length=30)),
                ('download_profile_label', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': '4 Add Languages',
            },
        ),
        migrations.CreateModel(
            name='UserQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_no', models.IntegerField()),
                ('qualification_name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': '3. Qualifications',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_no', models.IntegerField()),
                ('role_name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': '2. Role Permissions',
            },
        ),
        migrations.CreateModel(
            name='UserRegisterationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=30)),
                ('telephone', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('address', models.TextField(max_length=130)),
                ('indian', models.BooleanField()),
                ('option', models.IntegerField()),
                ('role', models.IntegerField(default=3)),
                ('profile_picture', models.FileField(null=True, upload_to='profile_picture/')),
                ('resume', models.FileField(null=True, upload_to='resume/')),
                ('pan_card', models.FileField(null=True, upload_to='pan_card/')),
                ('adhar_card', models.FileField(null=True, upload_to='adhar_card/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '1. User Registration',
            },
        ),
        migrations.CreateModel(
            name='PageName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=30)),
                ('language_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_registeration.Language')),
            ],
        ),
        migrations.CreateModel(
            name='PageLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_label_class_name', models.CharField(max_length=30)),
                ('page_label_text', models.CharField(max_length=30)),
                ('page_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_registeration.PageName')),
            ],
        ),
        migrations.CreateModel(
            name='LevelModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_user', models.BooleanField()),
                ('view_user', models.BooleanField()),
                ('edit_user', models.BooleanField()),
                ('delete_user', models.BooleanField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_registeration.UserRole')),
            ],
        ),
    ]
