# Generated by Django 3.0.7 on 2020-06-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_template', models.FileField(upload_to='word_template')),
                ('json', models.FileField(upload_to='json')),
                ('signature', models.FileField(upload_to='signature')),
            ],
        ),
    ]
