# Generated by Django 3.0.6 on 2020-05-19 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predefine_roles', models.CharField(default='', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=70, unique=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(default='', max_length=200)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_and_role_management_with_jwt_token_authentication_app.Role')),
            ],
        ),
    ]
